version: "3.3"
services:

  postgres:
    container_name: postgres
    image: postgres:12.2
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5433:5432"

  zookeeper:
    image: debezium/zookeeper:1.1
    ports:
      - 2181:2181
      - 2888:2888
      - 3888:3888

  kafka:
    image: debezium/kafka:1.1
    ports:
      - 9092:9092
    links:
      - zookeeper
    environment:
      - ZOOKEEPER_CONNECT=zookeeper:2181

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"


volumes:
  postgres_data:
    driver: local