create table limits (
    id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    account varchar(100) not null,
    rate numeric(15,4) not null,
    withdrawalAmount int not null,
    dataMov timestamp not null,
    CONSTRAINT pk_limit primary key (id)
);
