CREATE TABLE conta (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	code varchar(100) not null,
	balance numeric(19,2) not null,
	dataMov timestamp not null,
	CONSTRAINT conta_pk PRIMARY KEY (id)
);

CREATE TABLE extrato (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	code varchar(100) not null,
	entrance numeric(19,2) not null,
	exit numeric(19,2) not null,
	balance numeric(19,2) not null,
	dataMov timestamp not null,
	conta_id int8 NOT NULL,
	CONSTRAINT fk_conta PRIMARY KEY (id),
	CONSTRAINT fk_extrato FOREIGN KEY (conta_id) REFERENCES conta (id)
);


create sequence hibernate_sequence